import React from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { useNavigate } from "react-router-dom";
import { faBackward } from "@fortawesome/free-solid-svg-icons";

export const TermsConditions = () => {
  const navigate = useNavigate();
  return (
    <div className="terms-conditions">
      <h1>Terms and Conditions </h1>
      <p style={{ textDecoration: "none", fontSize: "22px" }}>
        Please read the Terms and Conditions carefully before using
        Daraz.com.np. This electronic record is generated by a computer system
        and does not require any physical or digital signatures.
      </p>
      <h2>1. INTRODUCTION</h2>
      <p style={{ textDecoration: "none", fontSize: "19px" }}>
        Welcome to GadgetZone.com.np also hereby known as “we", "us" or
        "GadgetZone". We are an online marketplace and these are the terms and
        conditions governing your access and use of Daraz along with its related
        sub-domains, sites, mobile app, services and tools (the "Site"). By
        using the Site, you hereby accept these terms and conditions (including
        the linked information herein) and represent that you agree to comply
        with these terms and conditions (the "User Agreement"). This User
        Agreement is deemed effective upon your use of the Site which signifies
        your acceptance of these terms. If you do not agree to be bound by this
        User Agreement please do not access, register with or use this Site.
        This site is owned and operated by Daraz Kaymu Private Limited
        (Registration No.125263/71/72). The Site reserves the right to change,
        modify, add, or remove portions of these Terms and Conditions at any
        time without any prior notification. Changes will be effective when
        posted on the Site with no other notice provided. Please check these
        Terms and Conditions regularly for updates. Your continued use of the
        Site following the posting of changes to Terms and Conditions of use
        constitutes your acceptance of those changes.
      </p>
      <h2>2. CONDITIONS OF USE </h2>
      <h3 style={{ textAlign: "left", marginLeft: "1rem" }}>
        A. YOUR ACCOUNT{" "}
      </h3>
      <p style={{ textDecoration: "none", fontSize: "19px" }}>
        To access certain services offered by the platform, we may require that
        you create an account with us or provide personal information to
        complete the creation of an account. We may at any time in our sole and
        absolute discretion, invalidate the username and/or password without
        giving any reason or prior notice and shall not be liable or responsible
        for any losses suffered by, caused by, arising out of, in connection
        with or by reason of such request or invalidation. You are responsible
        for maintaining the confidentiality of your user identification,
        password, account details and related private information. You agree to
        accept this responsibility and ensure your account and its related
        details are maintained securely at all times and all necessary steps are
        taken to prevent misuse of your account. You should inform us
        immediately if you have any reason to believe that your password has
        become known to anyone else, or if the password is being, or is likely
        to be, used in an unauthorized manner. You agree and acknowledge that
        any use of the Site and related services offered and/or any access to
        private information, data or communications using your account and
        password shall be deemed to be either performed by you or authorized by
        you as the case may be. You agree to be bound by any access of the Site
        and/or use of any services offered by the Site (whether such access or
        use are authorized by you or not). You agree that we shall be entitled
        (but not obliged) to act upon, rely on or hold you solely responsible
        and liable in respect thereof as if the same were carried out or
        transmitted by you. You further agree and acknowledge that you shall be
        bound by and agree to fully indemnify us against any and all losses
        arising from the use of or access to the Site through your account.
        Please ensure that the details you provide us with are correct and
        complete at all times. You are obligated to update details about your
        account in real time by accessing your account online. For pieces of
        information you are not able to update by accessing Your Account on the
        Site, you must inform us via our customer service communication channels
        to assist you with these changes. We reserve the right to refuse access
        to the Site, terminate accounts, remove or edit content at any time
        without prior notice to you. We may at any time in our sole and absolute
        discretion, request that you update your Personal Data or forthwith
        invalidate the account or related details without giving any reason or
        prior notice and shall not be liable or responsible for any losses
        suffered by or caused by you or arising out of or in connection with or
        by reason of such request or invalidation. You hereby agree to change
        your password from time to time and to keep your account secure and also
        shall be responsible for the confidentiality of your account and liable
        for any disclosure or use (whether such use is authorised or not) of the
        username and/or password.
      </p>
      <h3 style={{ textAlign: "left", marginLeft: "1rem" }}>B. PRIVACY </h3>
      <p style={{ textDecoration: "none", fontSize: "19px" }}>
        Please review our Privacy Agreement, which also governs your visit to
        the Site. The personal information / data provided to us by you or your
        use of the Site will be treated as strictly confidential, in accordance
        with the Privacy Agreement and applicable laws and regulations. If you
        object to your information being transferred or used in the manner
        specified in the Privacy Agreement, please do not use the Site.
      </p>
      <h3 style={{ textAlign: "left", marginLeft: "1rem" }}>
        C. PLATFORM FOR COMMUNICATION{" "}
      </h3>
      <p style={{ textDecoration: "none", fontSize: "19px" }}>
        You agree, understand and acknowledge that the Site is an online
        platform that enables you to purchase products listed at the price
        indicated therein at any time from any location using a payment method
        of your choice. You further agree and acknowledge that we are only a
        facilitator and cannot be a party to or control in any manner any
        transactions on the Site or on a payment gateway as made available to
        you by an independent service provider. Accordingly, the contract of
        sale of products on the Site shall be a strictly bipartite contract
        between you and the sellers on our Site while the payment processing
        occurs between you, the service provider and in case of prepayments with
        electronic cards your issuer bank. Accordingly, the contract of payment
        on the Site shall be strictly a bipartite contract between you and the
        service provider as listed on our Site.
      </p>
      <button className="Back-btn" onClick={() => navigate(-1)}>
        <FontAwesomeIcon icon={faBackward} className="backwardicon" size="1x" />
        Go Back
      </button>
    </div>
  );
};
